### ISSUE TITLE
KeyError [Bug]

### ISSUE THREAD

**Issue by jonwaland** [tomaae/homeassistant-portainer#38]
## Describe the issue
Getting KeyError: errors in log

## How to reproduce the issue
unknown

## Expected behavior
no error

## Software versions

 - Home Assistant version: HA CORE 2024.7.2
 - Portainer integration version: v 1.0.2
 - Portainer software version: Community Edition 2.19.5

## Diagnostics data
none

## Traceback/Error logs
```
2024-07-16 18:01:34.262 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
    self.async_update_listeners()
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/home/homeassistant/.homeassistant/custom_components/portainer/entity.py", line 114, in _handle_coordinator_update
    self._data = self.coordinator.data[self.description.data_path][self._uid]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'bd807a5a7ce5d0b970d12819dd796593f9d9668a9e9faa3b370cbfa1c58aa372'
```

## Additional context
none

**Comment by tomaae** [comment]
thats a strange one. can you post debugs?

**Comment by jonwaland** [comment]
I've restarted HA, and of course, the error has disappeared again. I've had it at occur multiple times (and then stop after a restart) about 3 times now. I'll set up debug and wait...

**Comment by jonwaland** [comment]
got a debug - apologies for size
[home-assistant_portainer_2024-07-19T02-07-20.232Z.log](https://github.com/user-attachments/files/16301153/home-assistant_portainer_2024-07-19T02-07-20.232Z.log)

**Comment by PHeonix25** [comment]
This is happening for me near-constantly. Happy to generate a debug log if it'll help.
For now, please feel free to add this screenshot to the original issue: 
![image](https://github.com/user-attachments/assets/3dd246f7-c082-4c36-964f-2274e18254cc)

**Comment by jonwaland** [comment]
bump

**Comment by jonwaland** [comment]
OK - this error occurs when a container is removed (docker rm ....). the reported keyerror is the removed container.

**Comment by jonwaland** [comment]
bump again

**Comment by jonwaland** [comment]
bump

**Comment by jonwaland** [comment]
bump

**Comment by jonwaland** [comment]
bumpitybump

**Comment by jonwaland** [comment]
bumpitybump

**Comment by PHeonix25** [comment]
@jonwaland -- I'll take this one: 

**bump** 

😁

**Comment by imposibrus** [comment]
No stale labels on my watch 😁

**Comment by jonwaland** [comment]
bumpity bump bump

**Comment by PavelD** [comment]
I have the same issue as well.

**Comment by jonwaland** [comment]
bump

**Comment by imposibrus** [comment]
bump

**Comment by jonwaland** [comment]
notstale

**Comment by PavelD** [comment]
I hope this issue has been addressed in https://github.com/tomaae/homeassistant-portainer/pull/52
