### ISSUE TITLE
[Bug] HA log full of errors when mikrotik custom integraton installed

### ISSUE THREAD

**Issue by Dillton** [tomaae/homeassistant-portainer#44]
## Describe the issue

Hi, I just added portainer and I see these errors in log:
Logger: homeassistant.util.logging
Source: util/logging.py:95
First occurred: 15:18:05 (36 occurrences)
Last logged: 15:19:04

Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7fea06b19b80>,) Traceback (most recent call last): File "/config/custom_components/mikrotik_router/entity.py", line 121, in async_update_controller data = coordinator.data[entity_description.data_path] ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'health'
Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7fea06b19b80>,) Traceback (most recent call last): File "/config/custom_components/mikrotik_router/entity.py", line 121, in async_update_controller data = coordinator.data[entity_description.data_path] ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'ups'
Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7fea06b19b80>,) Traceback (most recent call last): File "/config/custom_components/mikrotik_router/device_tracker.py", line 75, in async_update_controller data = coordinator.data[entity_description.data_path] ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'host'
Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7fea06b19b80>,) Traceback (most recent call last): File "/config/custom_components/mikrotik_router/entity.py", line 121, in async_update_controller data = coordinator.data[entity_description.data_path] ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'script'
Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7fea06b19b80>,) Traceback (most recent call last): File "/config/custom_components/mikrotik_router/entity.py", line 121, in async_update_controller data = coordinator.data[entity_description.data_path] ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'fw-update'

Otherwise everything seems to be working.

## How to reproduce the issue

I guess to have installed portainer and mikrotik custom integration together?

## Expected behavior

Clean logs.

## Software versions

 - Home Assistant version: HA 2024.8.2
 - Portainer integration version: v1.0.2
 - Portainer software version: 2.20.1

**Comment by Dillton** [comment]
Still a problem

**Comment by Dillton** [comment]
Still present

**Comment by Dillton** [comment]
still present

**Comment by Dillton** [comment]
not stale

**Comment by Dillton** [comment]
still issue

**Comment by PavelD** [comment]
I have exactly the same issue :-(

**Comment by Dillton** [comment]
still issue

**Comment by Dillton** [comment]
still issue

**Comment by Dillton** [comment]
still issue

**Comment by Dillton** [comment]
still issue

**Comment by tomaae** [comment]
I seen this issue opened in mikrotik_router github.
Error itself does not make sense tho, make sure mikrotik_router files are original and not modified.

**Comment by Dillton** [comment]
I am sure no file was ever changed. Tomorrow I can try to redownload both integrations and test again.

**Comment by Dillton** [comment]
Hi again. Sorry for late reply. I triedtoday finally to clean install both Mikrotik and Portainer integrations.
Still seeing this once Portainer integration is set up.
```
Logger: homeassistant.util.logging
Source: util/logging.py:95
First occurred: 19:41:32 (12 occurrences)
Last logged: 19:41:32

Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7f1651999160>,) Traceback (most recent call last): File "/config/custom_components/mikrotik_router/entity.py", line 121, in async_update_controller data = coordinator.data[entity_description.data_path] ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'health'
Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7f1651999160>,) Traceback (most recent call last): File "/config/custom_components/mikrotik_router/entity.py", line 121, in async_update_controller data = coordinator.data[entity_description.data_path] ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'ups'
Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7f1651999160>,) Traceback (most recent call last): File "/config/custom_components/mikrotik_router/device_tracker.py", line 75, in async_update_controller data = coordinator.data[entity_description.data_path] ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'host'
Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7f1651999160>,) Traceback (most recent call last): File "/config/custom_components/mikrotik_router/entity.py", line 121, in async_update_controller data = coordinator.data[entity_description.data_path] ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'script'
Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7f1651999160>,) Traceback (most recent call last): File "/config/custom_components/mikrotik_router/entity.py", line 121, in async_update_controller data = coordinator.data[entity_description.data_path] ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'fw-update'
```
